### ISSUE TITLE
Investigate moxygen as a our XML (C++) to markdown parser

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/docs#22]
https://github.com/sourcey/moxygen

Currently we use a custom script https://github.com/dronecore/DroneCore/blob/master/generate_markdown_from_doxygen_xml.py

**Comment by hamishwillee** [comment]
I ran our source though MOxygen - you can see [output here](https://hamishwillee.gitbooks.io/dronecore/content/v/cd9029b2b57e644c5754b1d48230d2d9936029b4/en/api_reference/apimoxygen.html) and sidebar for "our" output.
There are some bugs in rendering and everything is forced into one doc - possibly can be fixed.

At the moment I prefer our rendering, though this does have some "more correctness"

**Comment by julianoes** [comment]
What is "more correct"?

**Comment by hamishwillee** [comment]
That was a bit of a throwaway comment. What I should have said is that this probably covers a broader set of doxygen output - I just tested on our API, while this will have been tested on more examples. It is however still pre 1.0 release, and in no way any sort of defacto standard. 
There are also rendering errors. 

I prefer our rendering. We should revisit this in future though.

**Comment by julianoes** [comment]
Agreed, I think you did a nice job with your script for our use-case.

**Comment by hamishwillee** [comment]
Closing for now. Initial investigation showed no benefit. Maybe worth revisiting past gRPC
