### ISSUE TITLE
Update Unit/Integration tests guide

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [dronecore/docs#76]
@hamishwillee 
As per this [commit](https://github.com/dronecore/DroneCore/commit/9c9e9288421412446e2b649a8be9040dd7503ed5), we need to accordingly update guide to run unit and integration tests [here](https://docs.dronecore.io/en/contributing/test.html#testing).

**Comment by hamishwillee** [comment]
Thanks. Will do next week.

**Comment by julianoes** [comment]
Thanks @shakthi-prashanth-m and @hamishwillee!

**Comment by hamishwillee** [comment]
Yes, and thanks also to @shakthi-prashanth-m for notifying me about this. It is very easy to miss possible docs changes in technical PRs, so good to highlight them.
