### ISSUE TITLE
Gimbal, Follow Me missing in API Overview

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [dronecore/docs#81]
Hi @hamishwillee we need to update [API Overview](https://github.com/dronecore/DroneCore#api-overview) by adding Gimbal & Follow Me plugins to the list.

Thanks.

**Comment by hamishwillee** [comment]
@shakthi-prashanth-m Hmmm. The overview you're pointing me to is the README for dronecore/dronecore (not the docs). We don't support gimbal or followme in a release yet (only in develop). 

I will fix up the docs develop readme, but I don't think we should update the official readme until those appear in a release/are in master.

**Comment by hamishwillee** [comment]
OK, so docs "develop" readme already had Gimbal. I added Follow me: https://github.com/dronecore/docs/pull/83

I will close this. Feel free to open another in /dronecore repo for tracking that readme update - once we make a release

**Comment by shakthi-prashanth-m** [comment]
OK. Thanks.
Both [FollowMe](https://github.com/dronecore/DroneCore/tree/master/plugins/gimbal) & [Gimbal](https://github.com/dronecore/DroneCore/tree/master/plugins/follow_me) are in master.

**Comment by hamishwillee** [comment]
Ah, in that case you're right - sorry! Reopening. No point you having to create another issue. Will sort out tomorrow

**Comment by shakthi-prashanth-m** [comment]
OK

**Comment by hamishwillee** [comment]
Done - https://github.com/dronecore/DroneCore/commit/af1152bb165ce0fb08a01a88ab4bc80df0b5b587

**Comment by shakthi-prashanth-m** [comment]
Thanks @hamishwillee
