### ISSUE TITLE
Building Source · Need to retest docker commands

### ISSUE THREAD

**Issue by hamishwillee** [dronecore/docs#85]
[Building Source > Building in Docker](https://docs.dronecore.io/v/develop/en/contributing/build.html#building-in-docker) was written when we just had one Dockerfile in root. Now there are multiple files here:  https://github.com/dronecore/DroneCore/tree/develop/docker

Need to confirm instructions still OK.

**Comment by julianoes** [comment]
Nice catch, there are now two dockerfiles: https://github.com/dronecore/DroneCore/tree/master/docker

One for Ubuntu and one for Fedora. To build you know need to specify which file:

```
docker build -f docker/Dockerfile-Fedora-27 -t my_image .
```

**Comment by hamishwillee** [comment]
Done!
